name: 🚀 Deploy KingDefrag Python 3.11

on:
  push:
      branches: [main]

      jobs:
        deploy:
            runs-on: ubuntu-latest
                steps:
                    - uses: actions/checkout@v4
                        - uses: actions/setup-python@v4
                              with:
                                      python-version: '3.11'
                                          - run: |
                                                  cat > app.yaml << EOF
                                                          runtime: python311
                                                                  service: kingdefrag
                                                                          EOF
                                                                              - run: |
                                                                                      cat > main.py << EOF
                                                                                              from flask import Flask, jsonify
                                                                                                      app = Flask(__name__)
                                                                                                              @app.route('/')
                                                                                                                      def home():
                                                                                                                                  return '<h1>KingDefrag Python 3.11 - Modernizado!</h1>'
                                                                                                                                          if __name__ == '__main__':
                                                                                                                                                      app.run(host='0.0.0.0', port=8080)
                                                                                                                                                              EOF
                                                                                                                                                                  - uses: google-github-actions/auth@v1
                                                                                                                                                                        with:
                                                                                                                                                                                credentials_json: ${{ secrets.GCP_SA_KEY }}
                                                                                                                                                                                    - uses: google-github-actions/setup-gcloud@v1
                                                                                                                                                                                          with:
                                                                                                                                                                                                  project_id: kinggroup-website
                                                                                                                                                                                                      - run: gcloud app deploy --quiet --no-cache
