name: 🚀 Deploy KingDefrag Python 3.11

on:
  push:
      branches: [ main ]

      env:
        PROJECT_ID: kinggroup-website

        jobs:
          deploy:
              runs-on: ubuntu-latest
                  steps:
                      - uses: actions/checkout@v4
                          - uses: actions/setup-python@v4
                                with:
                                        python-version: '3.11'
                                            - uses: google-github-actions/auth@v2
                                                  with:
                                                          credentials_json: ${{ secrets.GCP_SA_KEY }}
                                                              - uses: google-github-actions/setup-gcloud@v2
                                                                    with:
                                                                            project_id: ${{ env.PROJECT_ID }}
                                                                                - run: |
                                                                                        echo "runtime: python311" > app.yaml
                                                                                                echo "service: kingdefrag" >> app.yaml
                                                                                                        echo "Flask==3.0.0" > requirements.txt
                                                                                                                echo "from flask import Flask, jsonify" > main.py
                                                                                                                        echo "app = Flask(__name__)" >> main.py
                                                                                                                                echo "@app.route('/')" >> main.py
                                                                                                                                        echo "def home():" >> main.py
                                                                                                                                                echo "    return jsonify({'service': 'KingDefrag', 'version': '3.11', 'status': 'online'})" >> main.py
                                                                                                                                                        echo "@app.route('/health')" >> main.py
                                                                                                                                                                echo "def health():" >> main.py
                                                                                                                                                                        echo "    return jsonify({'status': 'healthy'})" >> main.py
                                                                                                                                                                                echo "if __name__ == '__main__':" >> main.py
                                                                                                                                                                                        echo "    import os" >> main.py
                                                                                                                                                                                                echo "    app.run(host='0.0.0.0', port=int(os.environ.get('PORT', 8080)))" >> main.py
                                                                                                                                                                                                    - run: gcloud app deploy --quiet --promote
